- name: Execute ShellScript 
  hosts: workers
  become: true
  tasks:
    - name: Create a directory 
      file: 
        path: /home/vicheak/ansible-folder-test
        state: directory
        mode: 0755
    # - name: Copy file to remote server
    #   command: cp -r ../shellscript/* /home/vicheak/ansible-folder-test
    - name: Copy the shellscript to the remote server
      copy:
        src: ../shellscript/*
        dest: /home/vicheak/ansible-folder-test
        mode: 0755
    # - name: Execute the shellscript
    #   command: sudo /bin/bash /vicheak/test-folder/createfolder.sh